language: csharp
dist: trusty
mono: none
dotnet: 2.1.300
branches:
  only:
  - master
script:
- dotnet restore
- dotnet build
deploy:
  provider: heroku
  app: saymyname-service
  api_key:
    secure: ikAO4hXMsFQV4GGxIvOccVW+etWTMKEzP+59QGU6gR3jmo38fA4d1dUZgLCE/X0XGVJPqwd807vU6Qz3QKg+6A/2mGPbhH/VP+QqZAmcynTAOMISwCpxrImZeNj57xClTrH9JCK7OyV/1e0Y70mpxO3XnpkrT4ExVIaa/xJpJBvLgZMMWQe6rRxvZvESxInks39NKOYW8kK//5GPLWuxqAEdeXIr4pF7FXccxDidrlEvobLsPmkvLKQ6vkpQjW7gBgcXBp2KoeoFH2WbCICLHehUTNuLZHXkWD0kTtytxRJky0qqDrl32fpBnsbKv1o1f4CBIeYujHFWue1Pn8d7wHfmdDumdMO5WI335lW61hdUEjtl+6jAjMpnDpPH25I9G/R5awFsIL9b/y3VXYX1SHuUOcgr7Q6li6VUQyE/qOPc0eBOtASsW266yvqNa/n7Cf1EDAvjUifoC2UH0aqNIx4qZYMHUGQFlahvu3F/nG0rJ1acn/WBfRPDV6BzOgXPZyKgXMnAcvxeq0IpWGH99szWDkyUXhnjxIYnjW+Bh+QF/jOncLSg3P7+Wswt0IZWeFpYkzYDuKXsKHE/orlF3a/QqfbvDfAP+PVPFHY58mJ383Nuje6NwNJpjoQUFnTX4bYqVp8PmtcrmQ2UG3ZDxpkCKVLKz6+J9V4wAdfqiHg=