language: csharp
dist: trusty
mono: none
dotnet: 2.1.300
branches:
  only:
  - master
script:
  - dotnet restore
  - dotnet build
  - dotnet test -c Release
deploy:
  provider: heroku
  app: saymyname-service
  api_key:
    secure: ie7nrJ6+r7xYJcBlmo3uf8xOrvYHf7HwiwAsUGIgrSD2abXNJb8hui47KSHL7QsUrfBS77oXRGxAFGYrJB9fbcHeskS0yvo+Z51XncJO8Bmif0chJytDiopcK/XeyGjlUA2jntfU6FJhKXyUKV4lbgDqLr6+spgJWihNLZYt2qZZsaPgL/yYbVDknL+6bTCMh+e9ZstYXgQ8ncNV4d7qGdhS3eSjZSRtoTu6YlzIodpMTJkqMO+J+GH8QPdX1ebQE+tYaSUe1K1L4V2HOh+zd1TZ/UmCpPVenwa38YI1yHWe4q6FOEeVf5jIdRGEQ+VDm4I+6yUahlxvDHTmi9VGqC35ZsCBnJPps7yAQTzXAeYP4nCUWBD6pIsmJD1U5oCE95o0dgEELgoo2feEIBvyVOrZ+MJpXBrN5sruPSRLJNM+sQpQ8QGCUh1hTFfU/ZZio1cVV9pU52oWEawM4yqVTRrVEoAdJmdiE3rCC/vyhFrSp3j7ZcKWAhd8PnzmEcGIHqVDB0d7VMOj3apr/Y7ouSfMJJT1h/YOxmrPWNuSRkMm0qKt6PaEtG6aCF9ydcF15D5S+XpQenGnABC3U55nCotdiLXUIpuapjSw3Ekh08oyGkTuynMjYZVuwNvUtIEwanFGsO9FVk+ycz0yNCuOU/SIPm67OCyPh36V8MU6Zks=
