language: csharp
dist: trusty
mono: none
dotnet: 2.1.300
branches:
  only:
    - master
script:
  - dotnet restore
  - dotnet build
deploy:
  provider: heroku
  app: saymyname-service
  api_key:
    secure: ZA1mDBO7CBYwbMo2iigA9Wf/mMuAYClxO2fC5OjDskhv5krjcMXDIOQYFDlKWcw+1C8BWTocxr/pMIrRIeCURaRMM35CHVtBpClBu9DpO1ts9kDXbnHT4hgSQLN5TRXXQRYTjB26DjaYT8eOnDz0meg0QZapZpwQQlPFJ/w8OIjYFroMQf1I1UDwGE6Fu13PVjf7c11yAM8EjQHkAXAOcnxFhM5mPeVbiZyHoAVbP2dWdl1xKxfbyru3PcZolvat74/twX/E1h6eCj0vN0/dhQW++WtA8VW/bUOshYtvwAqbADJmhRAkC8xA/2GhsC+N/OqdmELMNYIOOmESeABV3uxfV8bvJXy8hysPF1CTo+mS3RyXxxuH8IbTQ3JH6LIKCZZ/Jk0EG+kup0iaYpHkeqtQo6zmD0apxemvPJBmzNWCvaL9KmiDVIaCh+yKhfmKR3uGGWWEMXR32tqb3PyI4S6urmjqeVxy6FjTIotsmYoQT52oyTI8U90sQYfPg1nFUmdzx4jcO6kydT1USrKbLuBGhw3VV+3A7I+nRr52LQRl4HfAsAkxJx340FJxc9s0/78sWkM6bNbhgg0HWJG4Xa74Q3vzyspUL/BCoDuGhZSjqjxq+gVAKBFCiR8NpY0p1uIeoe9nyztWXuXBG0hy6M03h0FSpeUBPq9RfdC88Ho=
