language: csharp
dist: trusty
mono: none
dotnet: 2.1.300
branches:
  only:
  - master
script:
- dotnet restore
- dotnet build
deploy:
  provider: heroku
  app: saymyname-service
  api_key:
    secure: hShJmcN39r1GipK60n/LHloLzQdmmJuTN5bUlhmU1T4vOFukj49j6p9o3dnTQGIiV8eDT0jkXwLxbvrkxGwTYOUChfKuzov3uRUGklr8y9MpTGNjtJXO95efWTfsF7wZfm7F+DKqn9VC3/R3b65kdu+0cbG7DWx/9Bpa7YXk5qREZcWHM8KpM6gUPWuCJBc0Jpv9x1PkrOAl/4yEemv6dKjmgNwG5VEcOK3JVgjrNV7ZfOoSHLrr6YUKFJbX1KL7SHAL3Z5xRrhqCjyyuOyoLB/rWbMNgX6jkkg1wVaNMk7H8AD/Zc/z5v3a+WpO0+Pe9MTAkxF0Ps/X4GdUS/dLcyjUYKUQ0A6mFNE68Nyu/ym+POnq3ruh9kXaF8k4+mu6KsOe0cVoj5KhhujAaXuTlMatZ+Jd4xiLE3IrOiOHSxROXU0H+w++IhXVssEgmnVTSmMmi/ifegkeXHW9PjiFZCIzWUpVzR377Vkj53hbRNk5oS2iGaR66kyJcgvNwKtZK1GrPV7a/DpfXzgBar58fYW0ACRF0dXtdKGAcIhG+WUNU0vixTo41dvCEvprWyKNl8+01vRmawKa5MAGpxt+/6OoVZyo6cQLt8WzpbGyU9T3b6NxftdVYd4X4e7yqPz9HeKye9FVoC1HW26PPDu8siOpnvBo2iRR4hbMNNDJ+HU=
