language: csharp
dist: trusty
mono: none
dotnet: 2.1.300
branches:
  only:
  - master
script:
- dotnet restore
- dotnet build
deploy:
  provider: heroku
  app: saymyname-service
  api_key:
    secure: ygEOplFQUEUVQd6/z42zbae3eIwpjqTtrYTgJHHDJK1L4GzodGZN4DQIQcBu4IL7UKqaqAv65NFd7WwyPBl4THX4euJNtV9lD9Ci/oHsKbMZC8SDVPsbECs1zpxbceeH6aq05E0WRF7J/QO5N29oTYbFZGZP7MV6DQz9I5qAE25J7CnQGSJZiUP4KS0Dt3V+bqsvNHJjEHR0mebpjxnkMOzvSC8px45F31sFZ6QgMioyqKuN9MMmE9YtuKqJk+qi4mOKSvV7TshCHfIeJPZUA4uYHdH5V2nzttHzUx1m5CVG+unoutnIvQciQoSCST5vE/dy9McAHBcsTVozekS26Aq5wplQnBu/HT4oKo39bHTfsUr2Q188EJyFTHINcEhAzpBbSC2l5UxdYNliBhRk9zogooYd+0NY0b/gfFUKs6MZYfCc8BgVxXFP3+t+B9iEhPvL5AkBqDCuSEFl3HeW4p8gbJu4HRK8Xd7kngUPA7WjsSLnvjFKLDwi98ZSPZyQtDAfQxSv4rWGw4yMjtzeyQLfztuzbraia6EHPrHRV4DoWUFpqgNTDnYrhXsOO/0lljEFMkh7I5QyUvqj827SMZc5XIJvIa/6gXOHcfvYnYo1j5Ny00eQL4K0XJgVcQP4Hhhuacxg4LVlgMKI4SRy1qmn5hSeLCpVf34mEpIRV3E=
env:
  global:
  - secure: 1BR6dKSgUYjAtraunWBLoTn8zh2iIviaxOps8v5sGsBgw3GOKBKPyzsU/IWFKBPwyrFyaJrEY3PcXT4r/ypsTnXrCgRChtLbhDB/RDjtMGrkI87dnpe7awVUYnXWuExUVyr8GXwq5KqQdWN9yfXAQlwWQZGMvxuz/6QIcphaIBG3WQ4p0coZOHw3iKSRtrOb5WGUkGiNHv2HvoketlkFpbcjwCnzWW9ToBX7gtFN/eZWyhJc98/YFYm7zi8XxsIh70I/8Ad1bo0gkQRAUZjA8JZlsEQbE4IqHtYFUh7gynHmafAMjn5u6thd8ULXihup5GqW1s7hSl21bwkauUIhBQZGSD4QY+vuQH7QvkYf++tmGUhxksnjobCpliT3yR41DoVE5tAajSazOcTKhsGKTXc7D0Y/KJGxhTWO9Jb50FtSleTdObdZUnTYyVDwRzY8BJEqQ/mK2U4J7Cm/FxyLnXI1sM88CXjRrXTWo9dGDlo1EGvneeAV7feth1K6ZPtaBtJvuph0a2HJKCjrZyd74SoMNZA1EuarFVMHeXYWpiUMgHz1p+khWAWJO3dlknpzPCfZWrBL52GUP1qBIWwAtpje9Ayd6PipLo+upGfUGzff1tRf02SCQUJf7/XJXJwYmavXvAlHhSLNfDr9kgSRFRVfAa52GusCqR7TzS8trjs=
  - secure: JTwbcBe1K7eVXLrmHN4Qnyj+93kmMrWYzKV5m6qD2+gcLimZW6txyjhVAYB26BQChr4L3MmSzasBvZ7llz1FAqwcE3ywhnrxSkyNZdft2WD9k9A4mpLtH2daZqfITdPCETM+GYjWLOnJ4FyVNTwhSnLygRqj0k9btug1qGoqgxiOdvbX7YFGLxlK/wF6WD0ijBtB4EsOT8Oh+ZLfHonOW5saadX1S3BeEo5T9m8gZ7vqclwokd6YRW36yldJ3pAwZsZhA4zBvBEWgPyQvZhlGSR4+GOiee690mrT+XQxmjN4r5t1cU2t7W1UuKrAASEBR81Z7dv7qgbjjl8J9deSriBAzhmGvbI7M9nypxNojWA+KQPHTe5nkG6iXqZeNztcQnRHyEFjbU0hi7WcQVKOg9Zt7i23gvcuH8aMnhnlKykwxh3q42aTr42cv8JV35JbpetnrQcM4SNKgM8UmFcSNqdURnX/FU4X2bnXqefs7LE4d/aT13H7m5+lpymYzkkicwnSy4TJZfTsLKf4vzYTfamiUMEqa3K5CAgHJJCzIPn/crn55x6WJu3ezBfDxSsaCOS40H3l4Pp7Fb8xHVjIt0pwr5Kh9+WZuNgcy0nw/ku5wD98jJIJFrrmbX/aiZ84ZnoT0pOuIljYZMsqDvC+sjWJy45sd30qLZETC8eKJzQ=
